### ISSUE TITLE
Ruby 2.7 deprecation warning

### ISSUE THREAD

**Issue by SebouChu** [sqreen/ruby-agent#3]
Hello! 

Reporting the following warning about the kwargs on Rails app boot:
```
/Users/sebastiengaya/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sqreen-1.21.0/lib/sqreen/graft/hook.rb:257: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/sebastiengaya/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-5.0.2/lib/rack/handler/puma.rb:62: warning: The called method `run' is defined here
```

Thanks in advance for the fix, keep the good vibe!

**Comment by lloeki** [comment]
Hello, and thanks for the report!

We have planned to go through those deprecation warnings in order to support Ruby 3.0, as they will become errors.

FYI the Ruby team decided to turn those warnings off with Ruby 2.7.2:

- https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/
- https://bugs.ruby-lang.org/issues/17000

**Comment by SebouChu** [comment]
Perfect! Thank you very much for your quick response 💪
